### ISSUE TITLE
Please update wiki with 6.8 kernel config changes

### ISSUE THREAD

**Issue by mkurz** [zzywysm/asahi-kernel-configs#1]
https://github.com/AsahiLinux/docs/wiki/Kernel-config-notes-for-distros needs to be updated for the 6.8 kernel:

- `CONFIG_APPLE_MBOX` was renamed to `CONFIG_APPLE_MAILBOX`
https://github.com/torvalds/linux/commit/c84292d9d253706267889cf2614400712f15d689

- `CONFIG_BT_HS` was removed (I can not select it anymore via `make menuconfig` with latest [kernel `asahi-6.8.9-5`](https://github.com/AsahiLinux/linux/releases/tag/asahi-6.8.9-5))
https://github.com/torvalds/linux/commit/e7b02296fb400ee64822fbdd81a0718449066333
https://github.com/torvalds/linux/commit/f4b0c2b4cd78b75acde56c2ee5aa732b6fb2a6a9

Thanks!

**Comment by zzywysm** [comment]
Fixed.  Thanks for noticing!

https://github.com/AsahiLinux/docs/wiki/Kernel-config-notes-for-distros/_compare/e9ae5bc5ed4ed25aaed44e8e37b5c9f9fc6a7c74...ac9ce4b8d0d11d05339920a0d98a2434d97c94b2
